# Generated by Django 3.1.2 on 2021-03-29 15:18

from django.db import migrations, models
import django.db.models.deletion
import regex


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[regex.validate_phone])),
            ],
            options={
                'verbose_name_plural': 'enquiries',
            },
        ),
        migrations.CreateModel(
            name='EnquiryEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('enquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_email', to='enquiry.enquiry')),
            ],
        ),
    ]
