# Generated by Django 3.1.2 on 2020-12-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_flower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='flower',
            name='colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_colour', to='products.colour'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_type', to='products.type'),
        ),
        migrations.AddField(
            model_name='flower',
            name='bouquet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower', to='products.bouquet'),
        ),
    ]
