# Generated by Django 3.1.2 on 2020-12-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201221_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='fave',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
