# Generated by Django 3.1.2 on 2020-12-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201224_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='bouquet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower', to='products.bouquet'),
        ),
    ]
