# Generated by Django 3.1.2 on 2021-01-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20210105_1950'),
        ('products', '0008_auto_20201230_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bouquet', to='basket.basket'),
        ),
    ]
