# Generated by Django 3.1.2 on 2021-01-07 11:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_basket_b_id_num'),
        ('products', '0011_auto_20210107_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='size',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='theme',
        ),
        migrations.CreateModel(
            name='ThemedBouquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themed_bouquet', to='basket.basket')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bouquet', to='products.size')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bouquet', to='products.theme')),
            ],
        ),
    ]
