# Generated by Django 3.1.2 on 2021-01-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210107_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='type',
        ),
        migrations.RemoveField(
            model_name='themedbouquet',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='themedbouquet',
            name='size',
        ),
        migrations.RemoveField(
            model_name='themedbouquet',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='ThemedBouquet',
        ),
    ]
