# Generated by Django 3.1.2 on 2021-01-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210113_2056'),
        ('products', '0013_auto_20210111_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bouquet', to='orders.order'),
        ),
    ]
