# Generated by Django 3.1.2 on 2021-01-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_bouquet_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='order',
        ),
    ]
