# Generated by Django 3.1.2 on 2020-12-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='bullshit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
