# Generated by Django 3.1.2 on 2020-12-31 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_basket_bullshit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='bullshit',
        ),
    ]
