# Generated by Django 3.1.2 on 2020-12-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_remove_basket_bullshit'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='co',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
