# Generated by Django 3.1.2 on 2021-01-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_basket_co'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='bouquet',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='co',
        ),
    ]
