# Generated by Django 3.1.2 on 2021-01-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20210105_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='b_id_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
