# Generated by Django 3.1.2 on 2021-01-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('basket', '0007_basket_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_basket', to='orders.order'),
        ),
    ]
