# Generated by Django 3.1.2 on 2021-01-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_basket_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='order',
        ),
    ]
