# Generated by Django 3.1.2 on 2021-01-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('range_products', '0004_auto_20210119_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangebouquet',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
    ]
