# Generated by Django 3.1.2 on 2021-01-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('range_products', '0005_rangebouquet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rangebouquet',
            name='order',
        ),
    ]
