# Generated by Django 3.1.2 on 2021-01-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themed_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themedbouquet',
            name='theme_name',
            field=models.CharField(choices=[('TYPE', 'Type'), ('COLOUR', 'Colour'), ('TYPE AND COLOUR', 'Type and Colour')], max_length=50, null=True),
        ),
    ]
