# Generated by Django 3.1.2 on 2021-01-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themed_products', '0003_auto_20210114_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themedbouquet',
            name='theme_name',
            field=models.CharField(blank=True, choices=[('Type', 'Type'), ('Colour', 'Colour'), ('Type and Colour', 'Type and Colour')], max_length=50, null=True),
        ),
    ]
