# Generated by Django 3.1.2 on 2021-01-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themed_products', '0005_rangebouquet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RangeBouquet',
        ),
    ]
