# Generated by Django 3.1.2 on 2021-01-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themed_products', '0006_delete_rangebouquet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themedbouquet',
            name='order',
        ),
    ]
