# Generated by Django 3.1.2 on 2021-01-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210113_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
