# Generated by Django 3.1.2 on 2021-01-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210113_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='o_total',
            new_name='order_total',
        ),
    ]
