# Generated by Django 3.1.2 on 2021-01-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('range_products', '0006_remove_rangebouquet_order'),
        ('products', '0015_remove_bouquet_order'),
        ('themed_products', '0007_remove_themedbouquet_order'),
        ('orders', '0004_auto_20210115_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_bouquet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='products.bouquet'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_rbouquet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='range_products.rangebouquet'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_tbouquet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='themed_products.themedbouquet'),
        ),
    ]
