# Generated by Django 3.1.2 on 2021-01-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210122_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_bouquet',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_rbouquet',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_tbouquet',
        ),
    ]
